name: BMI Calculator Tests

on:
  push:
    branches: [ main, dev-branch ]
  pull_request:
    branches: [ main, dev-branch ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build and run tests in Docker
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        load: true
        tags: bmi-calculator-tests:latest
        
    - name: Run tests
      run: |
        docker run --name bmi-tests bmi-calculator-tests:latest
        
    - name: Copy test results from container
      if: always()
      run: |
        docker cp bmi-tests:/app/test-results ./test-results
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install Robot Framework and robotframework-junit
      run: |
        pip install robotframework robotframework-junit
        
    - name: Convert Robot Framework output to JUnit format
      if: always()
      run: |
        python -m robot.run --rerunfailed NONE --output NONE --report NONE --log NONE --xunit test-results/junit.xml test-results/output.xml
        
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test-results/
        
    - name: Publish JUnit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: test-results/junit.xml
        check_name: "Robot Framework Test Results"
