name: BMI Calculator Tests

on:
  push:
    branches: [ main, dev-branch ]
  pull_request:
    branches: [ main, dev-branch ]
  workflow_dispatch:

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build and run tests in Docker
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        load: true
        tags: bmi-calculator-tests:latest
        
    - name: Run tests
      run: |
        docker run --name bmi-tests bmi-calculator-tests robot --outputdir /app/test-results /app/tests/BMICTests_datadriven.robot:latest
        
    - name: Copy test results from container
      if: always()
      run: |
        docker cp bmi-tests:/app/test-results ./tests/test-results/robotDatadriven/
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install Robot Framework
      run: |
        pip install robotframework
        
    - name: Convert to JUnit format
      if: always()
      run: |
        python -m robot.rebot --xunit ./tests/test-results/robotDatadriven/junit.xml ./tests/test-results/robotDatadriven/output.xml
        
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: ./tests/test-results/robotDatadriven/
        
    - name: Publish JUnit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: ./tests/test-results/robotDatadriven/junit.xml
        check_name: "Robot Framework Test Results"
